### ISSUE TITLE
Help with UV-82 "Ver NUV82" in key 3 presssed while turn on - "190923M" Key 6 pressed

### ISSUE THREAD

**Issue by jasr66** [bogde/uv5rtool#1]
Hi,

Sorry to bother you, but I need help with the UV-82HP radio with the NUV82 version, after trying to change the frequencies with CHIRP, all frequencies are now open and they cannot be moved again, it also seems to be the same type of situation as with the UV-5R that was solved with your tool.

If you need the initial image of the radio I can send it.

Thanks in advance,
José Rodrigues

**Comment by bogde** [comment]
Hi, José! It's difficult for me to give you a solution, since I don't own a UV-82HP and can't do any testing. If you send me the image file, I will take a look and I'll try to see if it's similar to the one from the UV-5R.

One thing that you could try would be to use Chirp to try and fix your radio, here's how:

1. Open Chirp and load your original image. You can even make changes to it, just make sure you keep a copy of the original file since it may be useful at some point.
2.  Go to Settings > Advanced Settings and change the Range Override Parameter from Default to UseAtOwnRisk (see image below)
<img width="558" alt="Screenshot 2023-05-04 090302" src="https://user-images.githubusercontent.com/644633/236126857-17fdda13-f3f3-448a-baa9-0043551b8f5f.png">
3. Upload the image to your radio as you would normally do.

I don't know if this is a new feature in Chirp or something that was there all along, I just stumbled upon it and tried it with my "defective" UV-5R, and seems to work fine.

Let me know how it goes!

Bogdan

**Comment by jasr66** [comment]
Hi again,

It's solved, thanks to you, thanks for the tip, when changing the **Range Override Parameter** from **Default** to **UseAtOwnRisk** Chirp uploads the image without errors and manages to change the frequencies as well as the rest of the parameters,
Thank you very much!!!

Anyway, I leave you the link here if you want the image of the UV-82HP from my version to study,

https://www.4shared.com/s/fWgaERMHLfa

Thank you very much!!!

**Comment by bogde** [comment]
You're welcome, glad it worked! Thanks for the file!
